version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

  jobs:
    post_create_environment:
      - "conda env export"
      - PLOOMBER_VERSION_CHECK_DISABLED=true

conda:
  environment: doc/environment.yml

sphinx:
  builder: html
  fail_on_warning: true
