name: ploomber-engine-doc

channels:
  - conda-forge


dependencies:
  - python=3.10
  - ipython
  - matplotlib
  - pandas
  - scikit-learn
  - pip
  - pip:
    - jupyter-book
    - jupytext
    - sklearn-evaluation
    - memory-profiler
    - pytest
    - ..
